version: "3.8"

services:
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - eureka.client.service-url.defaultZone=http://registry:8761/eureka
      - auth-service.uri=http://auth-service:8080
      - blog-service.uri=http://blog-service:8081
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
    depends_on:
      - registry

  maria-database:
    image: mariadb:11.3.2
    ports:
      - 3307:3306
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: sapassword
      MARIADB_ROOT_PASSWORD: sapassword
    volumes:
      - ./mariadb/data:/var/lib/mysql:Z

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://registry:8761/eureka
      - spring.datasource.url=jdbc:mariadb://maria-database:3306/auth-service-test?createDatabaseIfNotExist
      - spring.data.redis.host=redis
      - gateway.uri=gateway
      - gateway.port=8888
    depends_on:
      - registry
      - gateway
      - maria-database
      - redis
    restart: on-failure

  blog-service:
    build:
      context: ./BlogService
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - 8081:8081
    environment:
      - eureka.client.service-url.defaultZone=http://registry:8761/eureka
      - spring.datasource.url=jdbc:mariadb://maria-database:3306/blog-service-test?createDatabaseIfNotExist
      - spring.data.redis.host=redis
      - gateway.uri=gateway
      - gateway.port=8888
    depends_on:
      - registry
      - gateway
      - maria-database
      - redis
    restart: on-failure
