auth-service.uri: http://localhost:8080
blog-service.uri: http://localhost:8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: AuthService
          uri: ${auth-service.uri}
          predicates:
            - Path=/auth/**, /webjars/**
        - id: BlogService
          uri: ${blog-service.uri}
          predicates:
            - Path=/blog/**, /webjars/**
