spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: AuthService
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**, /webjars/**
        - id: BlogService
          uri: http://localhost:8081
          predicates:
            - Path=/blog/**, /webjars/**
